Se importa las bibliotecas de Pandas y Numpy para la manipulación del set de datos

In [2]:
# importa las bibliotecas Pandas y Numpy

import pandas as pd
import numpy as np

Cargamos el set de datos con la funcion de pandas read_csv('file_path'), en esta ocasión, vamos a utilizar un set de datos que trata acerca del analisis de riesgo de prestamos.
Leemos el set de datos y lo transformamos en un dataframe.

In [14]:
ubicacion = "./input/credit_risk_dataset.csv"
df = pd.read_csv(ubicacion)

Leemos las primeras 10 filas del dataframe y podemos verificar que efectivamente contienen encabezados, por lo que no sera necesario introducir uno. Loan_status es la variable target del set de datos, que determina si el prestamo se ha aprobado o no.

In [18]:
df.head(10)

Las primeras 90 filas del dataframe


person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0   
1          21           9600                   OWN                5.0   
2          25           9600              MORTGAGE                1.0   
3          23          65500                  RENT                4.0   
4          24          54400                  RENT                8.0   
5          21           9900                   OWN                2.0   
6          26          77100                  RENT                8.0   
7          24          78956                  RENT                5.0   
8          24          83000                  RENT                8.0   
9          21          10000                   OWN                6.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1   
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C       5500          12.87            1   
3     MEDICAL          C      35000          15.23            1   
4     MEDICAL          C      35000          14.27            1   
5     VENTURE          A       2500           7.14            1   
6   EDUCATION          B      35000          12.42            1   
7     MEDICAL          B      35000          11.11            1   
8    PERSONAL          A      35000           8.90            1   
9     VENTURE          D       1600          14.74            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                         Y                           3  
1                 0.10                         N                           2  
2                 0.57                         N                           3  
3                 0.53                         N                           2  
4                 0.55                         Y                           4  
5                 0.25                         N                           2  
6                 0.45                         N                           3  
7                 0.44                         N                           4  
8                 0.42                         N                           2  
9                 0.16                         N                           3

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   person_age                  32581 non-null  int64  
 1   person_income               32581 non-null  int64  
 2   person_home_ownership       32581 non-null  object 
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object 
 5   loan_grade                  32581 non-null  object 
 6   loan_amnt                   32581 non-null  int64  
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64  
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object 
 11  cb_person_cred_hist_length  32581 non-null  int64  
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB


Se verifica los datos nulos de la base de datos, en este caso la columna que presenta datos faltantes es el person_emp_length y el loan_int_rate con 895 y 3116 datos nulos respectivamente

In [23]:
datos_faltantes = df.isnull()
for columna in datos_faltantes.columns.values.tolist():
    print('columna:',columna)
    print (datos_faltantes[columna].value_counts())
    print("")    

columna: person_age
person_age
False    32581
Name: count, dtype: int64

columna: person_income
person_income
False    32581
Name: count, dtype: int64

columna: person_home_ownership
person_home_ownership
False    32581
Name: count, dtype: int64

columna: person_emp_length
person_emp_length
False    31686
True       895
Name: count, dtype: int64

columna: loan_intent
loan_intent
False    32581
Name: count, dtype: int64

columna: loan_grade
loan_grade
False    32581
Name: count, dtype: int64

columna: loan_amnt
loan_amnt
False    32581
Name: count, dtype: int64

columna: loan_int_rate
loan_int_rate
False    29465
True      3116
Name: count, dtype: int64

columna: loan_status
loan_status
False    32581
Name: count, dtype: int64

columna: loan_percent_income
loan_percent_income
False    32581
Name: count, dtype: int64

columna: cb_person_default_on_file
cb_person_default_on_file
False    32581
Name: count, dtype: int64

columna: cb_person_cred_hist_length
cb_person_cred_hist_length
False 

In [24]:
df.describe()

person_age  person_income  person_emp_length     loan_amnt  \
count  32581.000000   3.258100e+04       31686.000000  32581.000000   
mean      27.734600   6.607485e+04           4.789686   9589.371106   
std        6.348078   6.198312e+04           4.142630   6322.086646   
min       20.000000   4.000000e+03           0.000000    500.000000   
25%       23.000000   3.850000e+04           2.000000   5000.000000   
50%       26.000000   5.500000e+04           4.000000   8000.000000   
75%       30.000000   7.920000e+04           7.000000  12200.000000   
max      144.000000   6.000000e+06         123.000000  35000.000000   

       loan_int_rate   loan_status  loan_percent_income  \
count   29465.000000  32581.000000         32581.000000   
mean       11.011695      0.218164             0.170203   
std         3.240459      0.413006             0.106782   
min         5.420000      0.000000             0.000000   
25%         7.900000      0.000000             0.090000   
50%        10.990000      0.000000             0.150000   
75%        13.470000      0.000000             0.230000   
max        23.220000      1.000000             0.830000   

       cb_person_cred_hist_length  
count                32581.000000  
mean                     5.804211  
std                      4.055001  
min                      2.000000  
25%                      3.000000  
50%                      4.000000  
75%                      8.000000  
max                     30.000000

Vamos a manipular los datos faltantes, se va a realizar las siguientes manipulaciones:
- La columna person_emp_length vamos a manipularlo, reemplazando los 895 datos faltantes por su promedio
- La columna loan_int_rate vamos a manipularlo, reemplazando los 3116 datos faltantes por su promedio

In [ ]:
person_emp_length_mean = df["person_emp_length"].astype("float").mean(axis=0)
person_emp_length_mean

loan_int_rate_mean = df["loan_int_rate"].astype("float").mean(axis=0)
loan_int_rate_mean

df["person_emp_length"].replace(np.nan, person_emp_length_mean, inplace=True)
df["loan_int_rate"].replace(np.nan, loan_int_rate_mean, inplace=True)


- Reemplazar los Valores (N,Y) en (0,1) respectivamente, estos estan presentes en la columna cb_person_default_on_file
- 

In [33]:
df["cb_person_default_on_file"].replace('Y', 1, inplace=True)
df["cb_person_default_on_file"].replace('N', 0, inplace=True)

#Verificamos imprimiendo los primeros 10 valores si el reemplazo se ha realizado de manera correcta

df.head(10)

C:\Users\pc0123\AppData\Local\Temp\ipykernel_2412\1927637072.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["cb_person_default_on_file"].replace('Y', 1, inplace=True)
C:\Users\pc0123\AppData\Local\Temp\ipykernel_2412\1927637072.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a c

person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0   
1          21           9600                   OWN                5.0   
2          25           9600              MORTGAGE                1.0   
3          23          65500                  RENT                4.0   
4          24          54400                  RENT                8.0   
5          21           9900                   OWN                2.0   
6          26          77100                  RENT                8.0   
7          24          78956                  RENT                5.0   
8          24          83000                  RENT                8.0   
9          21          10000                   OWN                6.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1   
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C       5500          12.87            1   
3     MEDICAL          C      35000          15.23            1   
4     MEDICAL          C      35000          14.27            1   
5     VENTURE          A       2500           7.14            1   
6   EDUCATION          B      35000          12.42            1   
7     MEDICAL          B      35000          11.11            1   
8    PERSONAL          A      35000           8.90            1   
9     VENTURE          D       1600          14.74            1   

   loan_percent_income  cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                          1                           3  
1                 0.10                          0                           2  
2                 0.57                          0                           3  
3                 0.53                          0                           2  
4                 0.55                          1                           4  
5                 0.25                          0                           2  
6                 0.45                          0                           3  
7                 0.44                          0                           4  
8                 0.42                          0                           2  
9                 0.16                          0                           3

Vamos a realizar una manipulacion en la columna loan_intent, como podemos observar, hay 6 valores unicos en la columna que representan el proposito del prestamo, estos pueden ser personal, 

In [37]:
np.unique(df['loan_intent'])

array(['DEBTCONSOLIDATION', 'EDUCATION', 'HOMEIMPROVEMENT', 'MEDICAL',
       'PERSONAL', 'VENTURE'], dtype=object)

In [34]:
datos_faltantes = df.isnull()
for columna in datos_faltantes.columns.values.tolist():
    print('columna:',columna)
    print (datos_faltantes[columna].value_counts())
    print("")    

columna: person_age
person_age
False    32581
Name: count, dtype: int64

columna: person_income
person_income
False    32581
Name: count, dtype: int64

columna: person_home_ownership
person_home_ownership
False    32581
Name: count, dtype: int64

columna: person_emp_length
person_emp_length
False    32581
Name: count, dtype: int64

columna: loan_intent
loan_intent
False    32581
Name: count, dtype: int64

columna: loan_grade
loan_grade
False    32581
Name: count, dtype: int64

columna: loan_amnt
loan_amnt
False    32581
Name: count, dtype: int64

columna: loan_int_rate
loan_int_rate
False    32581
Name: count, dtype: int64

columna: loan_status
loan_status
False    32581
Name: count, dtype: int64

columna: loan_percent_income
loan_percent_income
False    32581
Name: count, dtype: int64

columna: cb_person_default_on_file
cb_person_default_on_file
False    32581
Name: count, dtype: int64

columna: cb_person_cred_hist_length
cb_person_cred_hist_length
False    32581
Name: count, dtype: i